### ISSUE TITLE
Question - What is this project and will it be used to fix the bugs in 06?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [HyperBE32/Marathon#11]
Is this for emulation console pc what is this project - what is its purpose? is it to make 06 finally playable they way it could have been with some TLC?

**Comment by Knuxfan24** [comment]
Marathon is a library designed to make modding '06 easier, by giving us nice simple ways to write code for editing the game's data files, on its own, Marathon does nothing, it's designed to be used for writing code for various tools.

**Comment by P3rf3ctXZer0** [comment]
Alright thank you.
