### ISSUE TITLE
App not responding if I open save *.bin and choose "Edit save data"

### ISSUE THREAD

**Issue by ru-web-designer** [HyperBE32/Marathon#14]
![image](https://user-images.githubusercontent.com/3310192/125179081-83d4dc80-e1f3-11eb-9be2-43a30392a5bb.png)

Save data file:
[SonicNextSaveData.zip](https://github.com/HyperBE32/Marathon/files/6796111/SonicNextSaveData.zip)

**Comment by Knuxfan24** [comment]
Basically none of the Toolkit functionality was ever done. If you want to edit the Save you'll have to write code yourself for it.

**Comment by ru-web-designer** [comment]
> Basically none of the Toolkit functionality was ever done. If you want to edit the Save you'll have to write code yourself for it.

Is that illegal to just leave this issue? :)

**Comment by HyperBE32** [comment]
Marathon is currently in the process of being rewritten and the UI will likely be moved to WPF - what you see is very unfinished and isn't a final release build.

**Comment by HyperBE32** [comment]
Also, your save file is an Xbox 360 STFS package - it needs to be extracted for Marathon to read it.
